project_name: oidc-config
release:
  github:
    owner: shundezhang
    name: oidc-config
builds:
  - id: oidc-config
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/shundezhang/oidc-config/pkg/version.version=
archives:
  - id: oidc-config
    builds:
    - oidc-config
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
