apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oidc-config
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/shundezhang/oidc-config/releases/download/v0.1.0/oidc-config_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./oidc-config"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oidc-config"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/shundezhang/oidc-config/releases/download/v0.1.0/oidc-config_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./oidc-config"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oidc-config"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/shundezhang/oidc-config/releases/download/v0.1.0/oidc-config_windows_amd64.zip
    sha256: ""
    files:
    - from: "/oidc-config.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "oidc-config.exe"
  shortDescription: A new plugin
  homepage: https://github.com/shundezhang/oidc-config
  caveats: |
    Usage:
      $ kubectl oidc-config

    For additional options:
      $ kubectl oidc-config --help
      or https://github.com/shundezhang/oidc-config/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
